name: PIS Electricity Meter
version: "0.3.16"
slug: pis_pis_meter
description: Scrapes PIS and shows you data.
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
  - i386
startup: services
boot: auto
init: false

webui: "http://[HOST]:[PORT:8080]/data"

ports:
  "8080/tcp": 8080

options:
  username: ""
  password: ""
  cache_ttl_seconds: 86400
  log_level: "INFO"

schema:
  username: str
  password: str
  cache_ttl_seconds: int(3600,604800)
  log_level: str?
